version: '3.8'  # Specify Docker Compose file format version

services:
  db:
    image: ankane/pgvector  # PostgreSQL image with PGVector extension included
    container_name: pgvector-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: telegram-bot
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db  # host inside Docker network
      POSTGRES_PORT: 5432
    command: python main.py  # entry point

volumes:
  pgdata: